### ISSUE TITLE
Running using Anaconda and Homebrew raises exceptions on MacOS sequoia

### ISSUE THREAD

**Issue by Jaapel** [lijun99/isce2-install#1]
Hi @lijun99 , thanks for creating these install guides!

Unfortuntely I still obtain some install errors when installing the software on my M3 macbook on sequoia (15).
Some errors like: `/opt/isce2/contrib/alos2filter/src/psfilt1.c:525:10: error: call to undeclared library function 'finite' with type 'int (double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`, which afaik mean that there are some library incompatibilties.
But also in the fftw3 calls.

Do you have some directions on where to look for solutions?

**Comment by lijun99** [comment]
I have updated the source code in order to be compatible with newer versions of GNU compilers (actually, the Apple Clang compiler now works as well. But you still need gfortran from homebrew.). Check out from the branch, https://github.com/lijun99/isce2/tree/modern-c. (git remote add lijun99 https://github.com/lijun99/isce2.git && git pull lijun99 modern-c) 

But use it as your own risk for now. It is to my understanding that the changes should not change the performance. But we should wait for the moderators/authors to approve. 

I have also updated the instructions for MacOS 15.1. Please check and let me know if you have any questions.

**Comment by Jaapel** [comment]
Looking good! I still see many compilation warnings, but I could use some basic parts of the isce2 code. Thanks for the update! I will be watching the related PR!

**Comment by Jaapel** [comment]
For future reference: https://github.com/isce-framework/isce2/pull/897
